version: '3'
services:
  airflow:
    build: .
    environment:
      # --- UPDATED CONFIGURATION ---
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW_ADMIN_USER=admin
      - AIRFLOW_ADMIN_PASSWORD=admin
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ../src:/opt/airflow/src
      - ../transform/my_pipeline:/opt/airflow/dbt
      - ~/.dbt:/opt/airflow/.dbt
      - ../.env:/opt/airflow/.env
    ports:
      - "8080:8080"
    # --- UPDATED COMMAND ---
    # We use 'db migrate' instead of 'db init', and we create the user safely.
    command: bash -c "airflow db migrate && airflow users create --username admin --password admin --firstname Peter --lastname Parker --role Admin --email spiderman@superhero.com && airflow webserver & airflow scheduler"
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow